# Generated by Django 4.1.1 on 2022-10-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipeingredient_recipe"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
