# Generated by Django 4.1.1 on 2022-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveIntegerField(null=True, verbose_name="Количество"),
        ),
    ]
