# Generated by Django 4.1.1 on 2022-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipeingredient_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(
                help_text="Введите время в минутах",
                verbose_name="Время приготовления, мин",
            ),
        ),
    ]
