# Generated by Django 4.1.1 on 2022-10-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_ingredient_name_alter_tag_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                fields=("author", "name"), name="unique_name"
            ),
        ),
    ]
