# Generated by Django 4.1.1 on 2022-10-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_recipe_pub_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("pub_date",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
    ]
